version : "3"
services:
  caipiao-mongo:
    image: mongo:3.7
    container_name: caipiao-mongo
    volumes:
      - ./.data/db:/data/db
    ports:
      - 27017:27017

  # caipiao-backend:
  #   environment:
  #     - NODE_ENV=dev
  #   container_name: caipiao-backend
  #   image: caipiao-backend
  #   build: .
  #   volumes:
  #     - ./:/app/
  #   command: npm run watch:debug
  #   ports:
  #     - 3000:3000
  #   links:
  #     - caipiao-mongo

  # swagger_ui:
  #   environment:
  #     - API_URL=/api_doc/main.yml
  #   image: swaggerapi/swagger-ui
  #   volumes:
  #     - ./api_doc:/usr/share/nginx/html/api_doc
  #   restart: always
  #   ports:
  #     - 9001:8080